version: "3"
services:
  db:
    container_name: db
    build: ./database
    ports:
      - "3306:3306"
    env_file:
      - ./WEB(BE)/src/db/.env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    networks:
      - miliroutine
  frontend:
    container_name: frontend
    build: ./WEB(FE)
    volumes:
      - "./WEB(FE)/:/app"
      - "/app/node_modules"
    expose:
      - 5173
    networks:
      - miliroutine
  backend:
    container_name: backend
    build: ./WEB(BE)
    restart: "on-failure"
    expose:
      - 3000
    volumes:
      - "./WEB(BE):/app"
    stdin_open: true
    tty: true
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm run start'
    depends_on:
      - db
    networks:
      - miliroutine
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: "on-failure"
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./WEB(FE)/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend

networks:
  miliroutine:
    driver: bridge
